services:
  postgres-iot:
    image: postgres:16-alpine
    container_name: postgres-iot
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iot_pass123
      POSTGRES_DB: iot_temperature
    ports:
      - "5432:5432"
    volumes:
      - postgres_iot_data:/var/lib/postgresql/data

volumes:
  postgres_iot_data:
